#+TITLE: Emacs configuration
:PROPERTIES:
#+AUTHOR: Rianne van Rees
#+STARTUP: fold
#+PROPERTY: header-args :results silent :tangle yes
:END:

This configuration is inspired by these sources:

- [[https://github.com/jakebox/jake-emacs/blob/main/jake-emacs/init.el][Jake-emacs]]
- [[https://github.com/reinout/.emacs.d][My father's configuration]]
- [[https://lucidmanager.org/productivity/configure-emacs/][Writing studio]]

If I edit the configuration, I can tangle the org file using the command C-c C-v t. Then, if I go to the init.el file, I can use the command M-x ev-b (eval-buffer) to reload the emacs configuration without having to close the program.

* Start of the init file

#+BEGIN_SRC emacs-lisp :tangle yes
  ;; Riannes emacs configuration.
  ;; This file is exported from emacs.org.
  ;; URL: https://github.com/riannevanrees/.emacs.d
#+END_SRC


* Package archive list

#+begin_src emacs-lisp :tangle yes
  (use-package package
    :config
    (add-to-list 'package-archives
                 '("melpa" . "https://melpa.org/packages/"))
    (package-initialize))
#+end_src


* Make sure emacs custom settings are written to custom.el

#+begin_src emacs-lisp :tangle yes
  (setq-default custom-file
                (expand-file-name "custom.el" user-emacs-directory))
  (when (file-exists-p custom-file)
    (load custom-file))
#+end_src


* Typing
** Auto-complete

This code snippet loads the package which-key. It displays the key bindings that can follow a currently incomplete command, after a default waiting time of 1 second. 

#+begin_src emacs-lisp :tangle yes
  (use-package which-key
  :ensure t
  :config
  (which-key-mode)
  )
#+end_src

** Line wrapping

It is frustrating is lines continue endlessly or words are continued on a different line, because a certain character limit is reached. The goal of this bit is to automatically wrap lines at 88 characters.

M-q fills the current paragraph. At the moment, the visual-fill-column-mode needs to be specifically enabled. This is done with the command C-c v. [[https://github.com/reinout/.emacs.d/blob/main/init.el][Here]] it is followed up with some code to undo the filling if necessary, so I can choose to implement that if I should need it.

#+begin_src emacs-lisp :tangle yes
  (use-package visual-fill-column
    :ensure t
    :init
    (add-hook 'visual-line-mode-hook #'visual-fill-column-mode)
    :bind ("C-c v" . visual-line-mode)
    )
 (setq-default fill-column 80)
#+end_src

** Shorten yes and no

#+begin_src emacs-lisp :tangle yes
  (setq use-short-answers t) ;; When emacs asks for "yes" or "no", let "y" or "n" suffice
#+end_src

** Line distance

I'd like this value to be higher, but at the moment it also lengthens the cursor and applies both to text and to code and for code the value of 1 works better.
#+begin_src emacs-lisp :tangle yes
  (setq-default line-spacing 1)
#+end_src
* Icons
#+begin_src emacs-lisp :tangle yes
  (use-package all-the-icons)
#+end_src

* Move backup files to a temporary directory

#+begin_src emacs-lisp :tangle yes
  (setq backup-directory-alist
            `((".*" . ,temporary-file-directory)))
#+end_src

* Theme

#+begin_src emacs-lisp :tangle yes
  (use-package gandalf-theme)
  (load-theme 'gandalf :no-confirm)
#+end_src

#+begin_src emacs-lisp :tangle no
  (use-package afternoon-theme)
  (load-theme 'afternoon t)
#+end_src

Disabled bit of code to load the modus vivendi theme. I disliked the look of the heading at level 2.
#+begin_src emacs-lisp :tangle no
  (use-package modus-themes
  :ensure t
  :config
  (setq modus-themes-italic-constructs t
	modus-themes-bold-constructs t)
  (load-theme 'modus-vivendi-tinted :no-confirm)
  )
#+end_src

* Org

** Custom TODO keywords
I edited the TODO keywords, so that I could see more easily where I was in the process.

#+begin_src emacs-lisp :tangle yes
      (setq org-todo-keywords
	    '((sequence "TODO" "|" "DONE" "CANCELLED")
	      (sequence "LEZEN" "VERZETTELEN" "|" "VOLTOOID" "GEANNUELEERD")
	      (sequence "LES" "VERZETTELEN" "|" "VOLTOOID" "GEANNULEERD")
	      (sequence "WACHTEN" "|" "VOLTOOID" "GEANNULEERD")))
#+end_src

** Use icons for headers and lists

#+begin_src emacs-lisp :tangle yes
  (use-package org-superstar
    :config
    (setq org-superstar-leading-bullet " ")
    (setq org-superstar-special-todo-items t) ;; Makes TODO header bullets into boxes
    (setq org-superstar-todo-bullet-alist '(("TODO" . 9744)
					    ("LES" . 9744)
					    ("LEZEN" . 9744)
					    ("VERZETTELEN" . 9744)
					    ("DONE" . 9745)
					    ("VOLTOOID" . 9745)))
    )
#+end_src

** Customize agenda

#+begin_src emacs-lisp :tangle yes
  (setq org-deadline-warning-days 7)
#+end_src

** Hide emphasis markers

#+begin_src emacs-lisp :tangle yes
  (use-package org-appear
    :commands (org-appear-mode)
    :hook (org-mode . org-appear-mode)
    :init
    (setq org-hide-emphasis-markers t		;; A default setting that needs to be t for org-appear
	org-appear-autoemphasis t		;; Enable org-appear on emphasis (bold, italics, etc)
	org-appear-autolinks nil		;; Don't enable on links
	org-appear-autosubmarkers t))	;; Enable on subscript and superscript
#+end_src

* Not yet done

** PDF-tools

** Org mode

** Short answers
** Look at frame settings in Jake B's init
