#+TITLE: Sleeping Beauty theme
#+DATE: 31 maart 2024

The colours of this theme are inspired by the Disney movie Sleeping Beauty, because that movie is colourful, but still looks very pretty, so this decision will hopefully not result in an angry fruit salad combination.

It also means that some colours can actually have a logical meaning:

- Warnings and errors can come in Maleficent's colours: purple and green.
- TODO and DONE states can be respectively pink and blue, referring to the pink-blue fight ("make it blue!").
- Red, which is often used for errors, is actually a positive colour in this theme, because it is associated with Philip.

This file contains the light theme. The intention is to also make a night theme, since the colours used for the night scenes in Sleeping Beauty are also pretty and are noticably different from the day theme. Flora's normally red dress becomes purple, for example.

This file will also contain a number of reference pictures of the movie, with colour references.

* Reference images

The reference images are in the sleeping-beauty-images folder.

* Color palettes

[[https://colorfulanimationexpressions.blogspot.com/2016/05/sumptuous-costume-colors-fairy-tale.html][This blog post]] contains an analysis of the colour use in the movie.

A lot of the colors in the film are actually muted by mixing it with black. That is why simply picking the actual color in the image gives a different look than the movie, because the color is viewed with its context. It also mixed several color palettes that are in the film.

- The *night* colour scheme, where the fairies have purple, green and blue dresses. They blend into the night more, but quite often, they are the only part of the frame that is still in the day color palette, particularly when they are flying. So the red-green-blue combination does not disappear entirely.
- The *fairies* each have their own hue: orange, green and blue. Strangely, while pink is clearly Flora's favourite color, she dresses in reds and oranges.
- In the *woods*, Aurora wears mostly grey colours. The brightness of the colours does vary, so that is why the dress still looks interesting. Philipp wears similar colours beneath his bright red cape. The red cape stands out very clearly in the green woods.
- The *royal* color palette contains blue, magenta, red, orange, yellow and black. It does not contain any green. Aurora's blue dress fits in rather well, the pink one feels slightly out of place.

 I think I want to use the *royal* colors for the day scheme and a combination of the *fairy* and *night* colour scheme for the night theme.

* Start of the theme code

#+begin_src emacs-lisp :tangle yes
  (require 'autothemer)
#+end_src

* Defining the theme

#+begin_src emacs-lisp :tangle yes
    (autothemer-deftheme
     sleeping-beauty "A theme inspired by the Sleeping Beauty movie"

     ((((class color) (min-colors #xFFFFFF))) ;; The theme is for graphical emacs

      ;; Defining the colour palette

      ;; Crowned
      (crowned-dress-dark    "#24257F")
      (crowned-dress-light   "#7880CB")
      (crown                 "#F1AB38")
      (crowned-red           "#7E0204")

      ;; Dragon
      (dragon-purple         "#3B2458")
      (dragon-green          "#85E11B")
      (dragon-yellow         "#E4CF30")
      (dragon-black          "#0D080B")
      (dragon-sky            "#808BB3")

      ;; Once upon a dream
      (dream-black           "#110713")
      (dream-tree            "#E3E7E3")
      (dream-tree-dark       "#D4DCDB")
      (dream-grass           "#B0C577")
      (dream-sky             "#A6C3CB")
      (dream-pink            "#C2ADC4")
      (dream-leaf            "#BBCF5D")

      ;; Fairies
      (merryweather          "#2F58CE")
      (merryweather-light    "#61ADDF")
      (fauna                 "#56930F")
      (fauna-light           "#88AD67")
      (flora                 "#9C181E")
      (flora-brown           "#7E673D")

      ;; Reunited
      (reunited-purple       "#C3A6E9")
      (reunited-dark-purple  "#633979")
      (reunited-yellow       "#F3A040")
      (reunited-red          "#870009")
      (reunited-crown        "#EDC32F")
      (reunited-blue         "#8891D2")
      (reunited-dark-blue    "#6F6FAF")

      ;; Dancing
      (dancing-blue          "#8ED9FC")
      (dancing-red           "#7F0115")

      ;; Sleeping
      (sleeping-sky          "#031D5F")
      (sleeping-sky-green    "#477278")
      (sleeping-crown        "#AF7906")
      (sleeping-fauna        "#72CDC5")
      (sleeping-fauna-dark   "#44A387")
      (sleeping-merryweather "#298ADC")
      (sleeping-flora        "#9D2D53")
      (sleeping-flora-dark   "#841535")
      (sleeping-curtain      "#451760")
      (sleeping-dark-blue    "#2A3FB2")
      (sleeping-light-blue   "#4971B2")
      (sleeping-rose         "#9D0104")
      (sleeping-dress-light  "#ACBFF7")
      (sleeping-dress-dark   "#4556E1")
      (sleeping-bed-green    "#6EBDC2")
      (sleeping-black        "#020D11")
      )

     ;; Customizing the faces
     ((default              (:foreground sleeping-black :background dream-tree :family "JuliaMono" :height 160))
     (variable-pitch        (:family "athelas" :height 1))

     (mode-line-active      (:background dream-sky)) ;dream-sky sleeping-dress-light
     (mode-line-inactive    (:background dream-tree-dark))
     (header-line           (:background sleeping-dress-light))
     (scroll-bar            (:background dream-tree-dark))
     (fringe                (:background dream-tree-dark))
     (cursor                (:background sleeping-black))

     (link                  (:foreground sleeping-fauna-dark :underline t))
     (highlight             (:background sleeping-rose)) ; Doesn't seem to be used at the moment.
     (region                (:foreground "#FFFFFF" :background sleeping-rose))
     (match                 (:foreground sleeping-rose))
     (isearch               ( :foreground "#FFFFFF" :background sleeping-rose))
     (lazy-highlight        (:background sleeping-rose))
     (error                 (:foreground dragon-green
  :background dragon-purple :weight 'bold))
     (success               (:foreground dancing-blue :weight 'bold))

     (font-lock-keyword-face   (:foreground merryweather))
     (font-lock-constant-face  (:foreground flora))
     (font-lock-string-face    (:foreground fauna))
     (font-lock-comment-face   (:foreground fauna-light))

     (org-document-title    (:foreground crown :weight 'bold :height 2.0))
     (org-document-info     (:foreground crowned-dress-light))
     (org-level-1           (:foreground crowned-dress-dark :weight 'bold :height 1.5))
     (org-level-2           (:foreground crowned-red :weight 'bold))
     (org-todo              (:foreground "HotPink"))
     (org-done              (:foreground dancing-blue :weight 'bold :slant 'italic))
     (org-headline-done     (:foreground dancing-blue :slant 'italic))

     (org-imminent-deadline (:foreground "green3" :weight 'bold))
     (org-upcoming-deadline (:foreground "Purple3" :weight 'bold))
     (org-scheduled-previously (:foreground "Purple3"))
     (org-scheduled-today   ())
     (org-headline-todo     (:foreground sleeping-black :weight 'bold))
     (org-agenda-done      (:foreground dancing-blue))
     (org-agenda-date-today  (:weight 'bold :height 2.0))
     (org-super-agenda-header  (:family "athelas" :weight 'bold :height 2.0))
     ))
#+end_src

* End of the theme code

#+begin_src emacs-lisp :tangle yes
  (provide-theme 'sleeping-beauty)
#+end_src
