;;; @-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from @.el

(register-definition-prefixes "@" '("def@" "describe-@" "with-@@"))


;;; Generated autoloads from @-mixins.el

(register-definition-prefixes "@-mixins" '("@immutable" "@soft-get" "@watchable"))

;;; End of scraped data

(provide '@-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; @-autoloads.el ends here
